### ISSUE TITLE
Android: Record Audio From Separate DeviceId and playback from different DeviceId

### ISSUE THREAD

**Issue by FazalHussain** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#632]
Hi,

I am exploring the superpower SDK and I would like to record audio from different device id and playback from different as we do with oboe SDK.

What I have tried so far

```
if (enableInput) { // Create the audio input buffer queue.
            internals->inputFifo.buffer = (short int *)malloc(internals->fifoBufferSizeBytes);

            //SLDataLocator_IODevice deviceInputLocator = { SL_DATALOCATOR_IODEVICE, SL_IODEVICE_AUDIOINPUT, SL_DEFAULTDEVICEID_AUDIOINPUT, NULL };
            SLDataLocator_IODevice deviceInputLocator = { SL_DATALOCATOR_IODEVICE, SL_IODEVICE_AUDIOINPUT, (SLuint32)inputDeviceId, NULL }; // Facing an error deviceid 13 is not valid
```

I am facing an error log like this

`2020-07-21 12:22:01.583 14543-14543/com.superpowered.effect E/libOpenSLES: pAudioSrc: invalid audio input deviceID=13`

Kindly tell can we do this with the superpower? If yes how can we do this

**Comment by gaborszanto** [comment]
Superpowered offers an open-source wrapper class around the OpenSL ES and AAudio audio APIs to set up audio I/O. This is very similar to Oboe, which is also a wrapper around the same APIs.

This open-source wrapper class is just a helper, not core Superpowered technology, since it's just using the Android APIs to set up audio I/O (the only way to do that): https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/blob/master/Superpowered/OpenSource/SuperpoweredAndroidAudioIO.cpp

Therefore your question is related to the OpenSL ES API, not Superpowered.

I see you replaced SL_DEFAULTDEVICEID_AUDIOINPUT to a specific device ID and you received the error "invalid audio input device". It means that the value you passed is not correct. How did you get the value of inputDeviceId?

**Comment by FazalHussain** [comment]
I am using the `AudioManager.registerAudioDeviceCallback ` to get the devices 

Snippet


```
        // Note that we will immediately receive a call to onDevicesAdded with the list of
        // devices which are currently connected.
        mAudioManager.registerAudioDeviceCallback(new AudioDeviceCallback() {
            @Override
            public void onAudioDevicesAdded(AudioDeviceInfo[] addedDevices) {

                List<AudioDeviceListEntry> deviceList =
                        AudioDeviceListEntry.createListFrom(addedDevices, mDirectionType);
                if (deviceList.size() > 0) {
                    mDeviceAdapter.addAll(deviceList);
                }
            }

            public void onAudioDevicesRemoved(AudioDeviceInfo[] removedDevices) {

                List<AudioDeviceListEntry> deviceList =
                        AudioDeviceListEntry.createListFrom(removedDevices, mDirectionType);
                for (AudioDeviceListEntry entry : deviceList) {
                    mDeviceAdapter.remove(entry);
                }
            }
        }, null);
```

Is there anything, I am doing wrong do let me know

**Comment by gaborszanto** [comment]
If you log it in Java, does it display 13 (the value you passed in the native layer)?

**Comment by FazalHussain** [comment]
Yes. It is logging 13.

**Comment by gaborszanto** [comment]
Maybe you need to leave the original source as it is and change it in Java before you create the native audio I/O, using this: https://developer.android.com/reference/android/media/AudioRouting#setPreferredDevice(android.media.AudioDeviceInfo)

**Comment by FazalHussain** [comment]
Thank you for your response so I have to record audio on java and then set the preference?  

I am just calling the native function to start the recording. 

If you have any supporting link so kindly share

**Comment by gaborszanto** [comment]
No, do not record in Java. Just set the routing preference in Java, before you call the native code to set up audio I/O.

**Comment by FazalHussain** [comment]
I am using the below snippet but it is not working

```
val audioRecord = AudioRecord(
                            MediaRecorder.AudioSource.DEFAULT,
                            samplerate, AudioFormat.CHANNEL_OUT_DEFAULT,
                            AudioFormat.ENCODING_PCM_16BIT,
                            buffersize)
                    audioRecord.preferredDevice = (recording_devices_spinner.selectedItem as AudioDeviceListEntry).deviceInfo
```

```
val audioTrack = AudioTrack(
                            AudioManager.STREAM_MUSIC,
                            samplerate,
                            AudioFormat.CHANNEL_OUT_MONO,
                            AudioFormat.ENCODING_PCM_16BIT,
                            buffersize,
                            AudioTrack.MODE_STREAM)

                    audioTrack.preferredDevice = (playback_devices_spinner.selectedItem as AudioDeviceListEntry).deviceInfo
```

Record and playback is for same device instead of the separate devices

**Comment by gaborszanto** [comment]
Looking at the Oboe documentation it seems like not even Oboe supports this feature, because of an unimplemented OpenSL ES routing feature: https://github.com/google/oboe/issues/228
Because Oboe was written by the Android audio team, it means that maybe there is no solution for your use case on Android.

**Comment by romanbsd** [comment]
AFAIK device id selection is only possible when using AAudio

**Comment by akilajwasala** [comment]
@FazalHussain Could you find a solution?

**Comment by balazsbanto** [comment]
Hi @akilajwasala  ,

Only `AAudio` supports device selection. In order to achieve this in Superpowered you have to do a few modifications in the `SuperpoweredAndroidAudio.cpp` file:

1.  Enable `AAudio` by settings `#define USE_AAUDIO 1`
2.  Get reference to the `AAudioStreamBuilder_setDeviceId ` function pointer. You can follow the convention used for the other `AAudio` functions, like `AAudioStreamBuilder_setSampleRate`.
3. Set the deviceID in the `startAAudio` function.

Hope this helps!
