### ISSUE TITLE
iOS + Bluetooth Hearing Aids, AU render callback issues

### ISSUE THREAD

**Issue by flagoworld** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#695]
With bluetooth hearing aids, the following values are provided by the OS to the coreAudioProcessingCallback:

    samplerate: 16000
    inNumberFrames: 512

Inside AudioIO, the min and max are as follows:

    int minimum = int(self->samplerate * 0.001f), maximum = int(self->samplerate * 0.025f);

That puts the maximum frames at 400. 512 > 400, which causes the processing callback to always return InvalidParameter and thus lock up the program.

There does not appear to be any negative side effects in this specific case to bypassing this check for min/max... Why does it exist and what is the proper way to fix this?

**Comment by gaborszanto** [comment]
There is no "proper way" to fix this, because SuperpoweredIOAudioIO is just an open-source helper class that you can change to your taste and use-case. It's impossible to deliver a class covering all, these values were primarily designed to have good audio quality with low latency and 16 kHz is outside of that.

You can just insert if (self->maximumNumberOfFrames < 1024) self->maximumNumberOfFrames = 1024; right after maximumNumberOfFrames is set.
