### ISSUE TITLE
SuperpoweredTimeStretching.rate can not work.

### ISSUE THREAD

**Issue by aheadlcx** [superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform#748]
SuperpoweredTimeStretching.rate can not work. And the Online demo, there is no such parameter to set.

https://docs.superpowered.com/reference/latest/time-stretching?lang=cpp

**Comment by ivannador** [comment]
From the documentation: 
_Notice that we removed the [rate](https://docs.superpowered.com/reference/latest/time-stretching?lang=cpp#rate-cpp) property, because it's logically impossible to speed up a realtime audio source and slowing down requires ever growing memory._

This means that in a real-time scenario the rate parameter does not make sense.
In order to use it, you have to input some offline audio source into the pipeline. Alternatively you can use AdvancedAudioPlayer with the built-in TimeStretching.

**Comment by aheadlcx** [comment]
I found that this rate property can not work in offline audio. I use this property in the recorder to play it after recording.

**Comment by ivannador** [comment]
Could you please share some code example of what you are trying to do exactly?
